#!/bin/sh
cd "$( dirname "$0" )"
tmux new -s bot -d 'mvn "-Dexec.args=-classpath %classpath de.Schnebi.BlubbspinatBot_MainClass" -Dexec.executable=java org.codehaus.mojo:exec-maven-plugin:1.5.0:exec 2>&1 | tee "logs/latest.log"'
